version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population_covid_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_2020 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_covid_2020.csv

  generate_study_population_general_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_2019 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_2019.csv

  generate_study_population_general_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_2020 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_2020.csv

  generate_study_population_pneumonia_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneumonia_2019 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_pneumonia_2019.csv

  matching_2019:
    run: python:latest python analysis/match_running.py "2019" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020, generate_study_population_general_2019]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_general_2019.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_general_2019.csv

  matching_2020:
    run: python:latest python analysis/match_running.py "2020" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020, generate_study_population_general_2020]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_general_2020.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_general_2020.csv

  reconcile_sick_note_spells_covid_2020:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_covid_2020" "input"
    needs: [generate_study_population_covid_2020]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_covid_2020_with_duration.csv

  reconcile_sick_note_spells_general_2019:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_general_2019" "matched_matches"
    needs: [matching_2019]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_general_2019_with_duration.csv

  reconcile_sick_note_spells_general_2020:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_general_2020" "matched_matches"
    needs: [matching_2020]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_general_2020_with_duration.csv

  reconcile_sick_note_spells_pneumonia_2019:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_pneumonia_2019" "input"
    needs: [generate_study_population_pneumonia_2019]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_pneumonia_2019_with_duration.csv

  covid_2020_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid_2020" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_covid_2020]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_covid_2020.dta

  general_2019_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "general_2019" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_general_2019]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_general_2019.dta

  general_2020_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "general_2020" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_general_2020]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_general_2020.dta

  pneumonia_2019_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "pneumonia_2019" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_pneumonia_2019]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_pneumonia_2019.dta

  covid_2020_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "covid_2020" --output-dir=output/tabfig
    needs: [covid_2020_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_covid_2020.csv

  general_2019_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "general_2019" --output-dir=output/tabfig
    needs: [general_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_general_2019.csv

  general_2020_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "general_2020" --output-dir=output/tabfig
    needs: [general_2020_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_general_2020.csv

  pneumonia_2019_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "pneumonia_2019" --output-dir=output/tabfig
    needs: [pneumonia_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_pneumonia_2019.csv

  append_cohorts:
    run: stata-mp:latest analysis/200_cr_data_management_matching.do --output-dir=output/cohorts
    needs: [covid_2020_rates_cohort, pneumonia_2019_rates_cohort, general_2020_rates_cohort, general_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        log: output/cohorts/append_cohorts.txt
      highly_sensitive: 
        dataset: output/cohorts/combined_covid_pneumonia.dta
        dataset2: output/cohorts/combined_covid_general_2019.dta
        dataset3: output/cohorts/combined_covid_general_2020.dta

  cox_models:
    run: stata-mp:latest analysis/201_cox_models.do
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models.txt
        dataset: output/tabfig/cox_model_summary.csv

  describe_duration_diagnoses:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/describe_duration_diagnoses.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [covid_2020_rates_cohort, general_2019_rates_cohort, general_2020_rates_cohort, pneumonia_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/describe_duration_diagnoses.html
        table: output/tabfig/med_mean_overall.csv
        table2: output/tabfig/med_mean_age_group.csv
        table3: output/tabfig/med_mean_sex.csv
        table4: output/tabfig/med_mean_ethnicity.csv
        table5: output/tabfig/med_mean_imd.csv
        table6: output/tabfig/med_mean_region.csv
        subplots: output/tabfig/num_diag_*.png 
        subplots2: output/tabfig/pct_diag_*.png

  rates_over_time:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/rates_over_time.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_study_population_covid_2020, generate_study_population_general_2019, generate_study_population_general_2020, generate_study_population_pneumonia_2019]
    outputs:
      moderately_sensitive:
        notebook: output/rates_over_time.html