version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population_covid_2020:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_covid_2020
      --output-dir=output/cohorts
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_covid_2020.csv.gz

  generate_study_population_covid_2021:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_covid_2021
      --output-dir=output/cohorts
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_covid_2021.csv.gz

  generate_study_population_general_match_vars_2019:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_general_match_vars
      --output-dir=output/cohorts
      --output-format=csv.gz
      --index-date-range="2019-02-01"
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_match_vars_2019-02-01.csv.gz

  generate_study_population_general_match_vars_2020:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_general_match_vars
      --output-dir=output/cohorts
      --output-format=csv.gz
      --index-date-range="2020-02-01"
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_match_vars_2020-02-01.csv.gz

  generate_study_population_general_match_vars_2021:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_general_match_vars
      --output-dir=output/cohorts
      --output-format=csv.gz
      --index-date-range="2021-02-01"
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_match_vars_2021-02-01.csv.gz

  generate_study_population_pneumonia_2019:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_pneumonia_2019
      --output-dir=output/cohorts
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_pneumonia_2019.csv.gz

  matching_2019:
    run: python:latest python analysis/match_running.py "2019" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020, generate_study_population_general_match_vars_2019]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_general_2019.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_general_2019.csv

  matching_2020:
    run: python:latest python analysis/match_running.py "2020" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020, generate_study_population_general_match_vars_2020]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_general_2020.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_general_2020.csv

  matching_2021:
    run: python:latest python analysis/match_running.py "2021" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2021, generate_study_population_general_match_vars_2021]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_general_2021.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_general_2021.csv

  generate_study_population_matched_2019:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_matched_2019
      --output-dir=output/cohorts
      --output-format=csv.gz
    needs: [matching_2019]
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_matched_2019.csv.gz

  generate_study_population_matched_2020:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_matched_2020
      --output-dir=output/cohorts
      --output-format=csv.gz
    needs: [matching_2020]
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_matched_2020.csv.gz

  generate_study_population_matched_2021:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_matched_2021
      --output-dir=output/cohorts
      --output-format=csv.gz
    needs: [matching_2021]
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_matched_2021.csv.gz

  reconcile_sick_note_spells_covid_2020:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_covid_2020"
    needs: [generate_study_population_covid_2020]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_covid_2020_with_duration.csv

  reconcile_sick_note_spells_covid_2021:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_covid_2021"
    needs: [generate_study_population_covid_2021]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_covid_2021_with_duration.csv

  reconcile_sick_note_spells_general_2019:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_matched_2019"
    needs: [generate_study_population_matched_2019]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_matched_2019_with_duration.csv

  reconcile_sick_note_spells_general_2020:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_matched_2020"
    needs: [generate_study_population_matched_2020]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_matched_2020_with_duration.csv

  reconcile_sick_note_spells_general_2021:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_matched_2021"
    needs: [generate_study_population_matched_2021]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_matched_2021_with_duration.csv

  reconcile_sick_note_spells_pneumonia_2019:
    run: python:latest python analysis/reconcile_sick_note_spells.py "_pneumonia_2019"
    needs: [generate_study_population_pneumonia_2019]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/cohorts/input_pneumonia_2019_with_duration.csv

  covid_2020_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid_2020" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_covid_2020]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_covid_2020.dta

  covid_2021_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid_2021" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_covid_2021]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_covid_2021.dta

  general_2019_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "matched_2019" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_general_2019]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_matched_2019.dta

  general_2020_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "matched_2020" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_general_2020]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_matched_2020.dta

  general_2021_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "matched_2021" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_general_2021]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_matched_2021.dta

  pneumonia_2019_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "pneumonia_2019" --output-dir=output/cohorts
    needs: [reconcile_sick_note_spells_pneumonia_2019]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_pneumonia_2019.dta

  covid_2020_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "covid_2020" --output-dir=output/tabfig
    needs: [covid_2020_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_covid_2020.csv

  covid_2021_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "covid_2021" --output-dir=output/tabfig
    needs: [covid_2021_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_covid_2021.csv

  general_2019_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "matched_2019" --output-dir=output/tabfig
    needs: [general_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_matched_2019.csv

  general_2020_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "matched_2020" --output-dir=output/tabfig
    needs: [general_2020_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_matched_2020.csv

  general_2021_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "matched_2021" --output-dir=output/tabfig
    needs: [general_2021_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_matched_2021.csv

  pneumonia_2019_rates:
    run: stata-mp:latest analysis/100_cr_simple_rates.do "pneumonia_2019" --output-dir=output/tabfig
    needs: [pneumonia_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_pneumonia_2019.csv

  append_cohorts:
    run: stata-mp:latest analysis/200_cr_data_management_matching.do --output-dir=output/cohorts
    needs: [covid_2021_rates_cohort, covid_2020_rates_cohort, pneumonia_2019_rates_cohort, general_2021_rates_cohort, general_2020_rates_cohort, general_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        log: output/cohorts/append_cohorts.txt
      highly_sensitive: 
        dataset: output/cohorts/combined_covid_2020_pneumonia.dta
        dataset2: output/cohorts/combined_covid_2021_pneumonia.dta
        dataset3: output/cohorts/combined_covid_2020_general_2019.dta
        dataset4: output/cohorts/combined_covid_2021_general_2019.dta
        dataset5: output/cohorts/combined_covid_general_2020.dta
        dataset6: output/cohorts/combined_covid_general_2021.dta

  cox_models:
    run: stata-mp:latest analysis/201_cox_models.do
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models.txt
        dataset: output/tabfig/cox_model_summary.csv

  cox_models_split_2020_pneumo:
    run: stata-mp:latest analysis/202_cox_models_split.do "2020_pneumonia"
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models_split_2020_pneumonia.txt
        dataset: output/tabfig/cox_model_split_summary_2020_pneumonia.csv

  cox_models_split_2021_pneumo:
    run: stata-mp:latest analysis/202_cox_models_split.do "2021_pneumonia"
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models_split_2021_pneumonia.txt
        dataset: output/tabfig/cox_model_split_summary_2021_pneumonia.csv
  
  cox_models_split_2020_gen_2019:
    run: stata-mp:latest analysis/202_cox_models_split.do "2020_general_2019"
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models_split_2020_general_2019.txt
        dataset: output/tabfig/cox_model_split_summary_2020_general_2019.csv
        
  cox_models_split_2021_gen_2019:
    run: stata-mp:latest analysis/202_cox_models_split.do "2021_general_2019"
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models_split_2021_general_2019.txt
        dataset: output/tabfig/cox_model_split_summary_2021_general_2019.csv

  cox_models_split_gen_2020:
    run: stata-mp:latest analysis/202_cox_models_split.do "general_2020"
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models_split_general_2020.txt
        dataset: output/tabfig/cox_model_split_summary_general_2020.csv
        
  cox_models_split_gen_2021:
    run: stata-mp:latest analysis/202_cox_models_split.do "general_2021"
    needs: [append_cohorts]
    outputs:
      moderately_sensitive:
        log: output/cohorts/cox_models_split_general_2021.txt
        dataset: output/tabfig/cox_model_split_summary_general_2021.csv

  describe_duration_diagnoses:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/describe_duration_diagnoses.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [covid_2021_rates_cohort, covid_2020_rates_cohort, general_2019_rates_cohort, general_2020_rates_cohort, general_2021_rates_cohort, pneumonia_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/describe_duration_diagnoses.html
        table: output/tabfig/med_mean_overall.csv
        table2: output/tabfig/med_mean_age_group.csv
        table3: output/tabfig/med_mean_sex.csv
        table4: output/tabfig/med_mean_ethnicity.csv
        table5: output/tabfig/med_mean_imd.csv
        table6: output/tabfig/med_mean_region.csv
        subplots: output/tabfig/diag_*.png 


  table1:
    run: r:latest analysis/1_table1_demo_clinical.R
    needs: [covid_2021_rates_cohort, covid_2020_rates_cohort, general_2019_rates_cohort, general_2020_rates_cohort, general_2021_rates_cohort, pneumonia_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        table: output/tabfig/table1_*.csv

  visualise_diagnoses:
    run: r:latest analysis/2_visualise_diagnoses.R
    needs: [covid_2021_rates_cohort, covid_2020_rates_cohort, general_2019_rates_cohort, general_2020_rates_cohort, general_2021_rates_cohort, pneumonia_2019_rates_cohort]
    outputs:
      moderately_sensitive:
        table: output/tabfig/diag_by_cohort.csv
        plot: output/tabfig/diag_all.png        

  check_missing:
    run: r:latest analysis/3_check_sick_note_duration.R
    needs: [covid_2021_rates_cohort, covid_2020_rates_cohort, general_2019_rates_cohort, general_2020_rates_cohort, general_2021_rates_cohort, pneumonia_2019_rates_cohort,
            generate_study_population_matched_2019, generate_study_population_matched_2020, generate_study_population_matched_2021,
            generate_study_population_covid_2020,generate_study_population_covid_2021, generate_study_population_pneumonia_2019]
    outputs:
      moderately_sensitive:
        table: output/tabfig/sick_note_missing*.csv
