version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input.csv

  generate_study_population_general_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_2019 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_2019.csv

  generate_study_population_general_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_2020 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_2020.csv

  generate_study_population_pneumonia_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneumonia_2019 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_pneumonia_2019.csv

  matching:
    run: python:latest python analysis/match_running.py --output-dir=output/cohorts
    needs: [generate_study_population, generate_study_population_general_2019, generate_study_population_general_2020]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_*.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_*.csv