version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population_covid_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_2020 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_covid_2020.csv

  generate_study_population_general_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_2019 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_2019.csv

  generate_study_population_general_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_2020 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_general_2020.csv

  generate_study_population_pneumonia_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneumonia_2019 --output-dir=output/cohorts 
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_pneumonia_2019.csv

  matching_2019:
    run: python:latest python analysis/match_running.py "input_general_2019" "_2019" "2019-02-01" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020, generate_study_population_general_2019]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_2019.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_2019.csv

  matching_2020:
    run: python:latest python analysis/match_running.py "input_general_2020" "_2020" "2020-02-01" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020, generate_study_population_general_2020]
    outputs:
      moderately_sensitive:
        matching_report: output/cohorts/matching_report_2020.txt
      highly_sensitive:
        matched_cohort: output/cohorts/matched_matches_2020.csv

  covid_2020_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid_2020" --output-dir=output/cohorts
    needs: [generate_study_population_covid_2020]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_covid_2020.dta

  general_2019_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "general_2019" --output-dir=output/cohorts
    needs: [generate_study_population_general_2019]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_general_2019.dta

  general_2020_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "general_2020" --output-dir=output/cohorts
    needs: [generate_study_population_general_2020]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_general_2020.dta

  pneumonia_2019_rates_cohort:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "pneumonia_2019" --output-dir=output/cohorts
    needs: [generate_study_population_pneumonia_2019]
    outputs:
      highly_sensitive:
        analysis_dataset: output/cohorts/cohort_rates_pneumonia_2019.dta